### ISSUE TITLE
Add English language.

### ISSUE THREAD

**Issue by Anonymous2716** [muslimpack/Qadaa#1]
For those of us don't speak Arabic fluently its a little hard to understand. And add new language `ENGLISH`  foemr the sentences but not the sensitive words like the wakt names Fajar dhuhur .  I couldn't get the theme working. Your app is on fdroid . add the link in README.

**Comment by Anonymous2716** [comment]
InshaAllah.

**Comment by mojienjoyment** [comment]
I want to translate it to English. I can't find any "String.xml" file. How can I translate it to Eng? @HasanEltantawy

**Comment by HasanEltantawy** [comment]
@mojienjoyment Insha'Allah I'll work on that as soon as I'm available .

**Comment by HasanEltantawy** [comment]
@mojienjoyment Done we have added some languages u can find translation files in lib\l10n
