### ISSUE TITLE
Bug: خيار صفحة البدء

### ISSUE THREAD

**Issue by 4mohamedaliii** [muslimpack/Qadaa#3]
لما بضغط على اختيار صفحة البدء مفيش اى رياكشن بيحصل
لما اقفل صفحة الإعدادات وافتحها تانى بلاقيها اتغيرت من لون ثابت الى صورة او العكس.
الاختيار مش بيتغير لحظة الضغط مش بيعمل ريفرش الا لما اطلع من الاعدادات وارجع ليها تانى

**Comment by HasanEltantawy** [comment]
@4mohamedaliii سنعمل على المشكلة في أقرب وقت ممكن إن شاء الله

**Comment by HasanEltantawy** [comment]
تم حل المشكلة وستصل مع التحديث القادم إن شاء الله
